### ISSUE TITLE
Can't provision a data source with an index

### ISSUE THREAD

**Issue by RichardChester** [grafana/open-distro-for-elasticsearch-grafana-datasource#37]
I hvae provisioned a data source using the following yaml 

```
apiVersion: 1

datasources:
    -   name: nElasticsearch
        type: elasticsearch
        access: proxy
        url: https://my.url
        jsonData:
            index: "project-17*"
            timeField: '@timestamp'
            version: '8.0.0'
            flavor: 'elasticsearch'
            logMessageField: message
            logLevelField: fields.level
```

however when I then run my grafana instance it provisions the data source exactly as I would expect however the index is left blank where I would expect it to be project-17*
